version: "3.8"

services:
# -----------------------------
# redis database
# -----------------------------
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - proxy_network
# -----------------------------
# postgres database
# -----------------------------
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - '15432:5432'
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge
    name: forward_proxy_network